
#' Generate a matrix of weights for the Bayesian Bootstrap
#'
#' @param N Length of the data
#' @param R Number of bootstrap replicates
#'
#' @returns A matrix of R rows and N columns with weights for the bootstrap. Rows should sum to 1
#' @rdname boot_mat
#' @export
#'
boot_mat <- function(N, R){
  mat <- gtools::rdirichlet(n = R, alpha = rep(1, N))
  return(mat)
}



#' Bayesian bootstrap helper functions
#'
#' @param data Vector of data to perform the bootstrap on
#' @param weights vector of weights to use in the bootstrap replicate
#' @name boots
NULL
#> NULL


#' @rdname boots
#' @export
mu_boot <- function(data, weights){
  sum(weights * data)
}

#' @rdname boots
#' @export
sd_boot <- function(data, weights){
  sqrt(sum(weights * (data - sum(data*weights))^2))
}

#' @rdname boots
#' @export
var_boot <- function(data, weights){
  sum(weights * (data - sum(data*weights))^2)
}

#' Perform Bayesian bootstrap
#'
#' @param data The data to be bootstrapped
#' @param R Number of bootstrap replicates, default = 1000
#' @param fun Function to calculate the statistic of interest
#'
#' @returns A vector representing the posterior of the statistic of interest (generated by fun)
#' @rdname b_boot
#' @export
#'
b_boot <- function(data, R = 1000, fun){
  mat <- boot_mat(N = length(data), R = R)
  return(apply(mat, 1, function(x) fun(data, x)))
}
